[[pandoc]]
arch = "aarch64"
git-tree-sha1 = "572f2ba4a70a4591306186b03d73d2c79365b580"
libc = "glibc"
os = "linux"

    [[pandoc.download]]
    sha256 = "3a92f43059fd0c47e81aacdf8e83c1a36dfcec9edab5add9009b600ab06bc73f"
    url = "https://github.com/JuliaBinaryWrappers/pandoc_jll.jl/releases/download/pandoc-v2.14.0+0/pandoc.v2.14.0.aarch64-linux-gnu.tar.gz"
[[pandoc]]
arch = "x86_64"
git-tree-sha1 = "c139fc60e2995c787d6c53e6113f46a745b2a626"
os = "macos"

    [[pandoc.download]]
    sha256 = "50db927b65175cbbd7fb8d1d03ff0fc2f28455820f781f46aa87255f1df2392c"
    url = "https://github.com/JuliaBinaryWrappers/pandoc_jll.jl/releases/download/pandoc-v2.14.0+0/pandoc.v2.14.0.x86_64-apple-darwin.tar.gz"
[[pandoc]]
arch = "aarch64"
git-tree-sha1 = "c139fc60e2995c787d6c53e6113f46a745b2a626"
os = "macos"

    [[pandoc.download]]
    sha256 = "50db927b65175cbbd7fb8d1d03ff0fc2f28455820f781f46aa87255f1df2392c"
    url = "https://github.com/JuliaBinaryWrappers/pandoc_jll.jl/releases/download/pandoc-v2.14.0+0/pandoc.v2.14.0.x86_64-apple-darwin.tar.gz"

[[pandoc]]
arch = "x86_64"
git-tree-sha1 = "4315774b120ac2cf172a58bc392626b12521b09b"
libc = "glibc"
os = "linux"

    [[pandoc.download]]
    sha256 = "a2e0b47563e318a849b6656996e7b63c961531beeb66147d281a645ebf59facc"
    url = "https://github.com/JuliaBinaryWrappers/pandoc_jll.jl/releases/download/pandoc-v2.14.0+0/pandoc.v2.14.0.x86_64-linux-gnu.tar.gz"
[[pandoc]]
arch = "x86_64"
git-tree-sha1 = "35cb82ecb1c17fced909f12b96a6c5f40aa56756"
os = "windows"

    [[pandoc.download]]
    sha256 = "1fe66e647a337053df47ae261e9243fa3218b6bb99e2a65d551840444fd1ad68"
    url = "https://github.com/JuliaBinaryWrappers/pandoc_jll.jl/releases/download/pandoc-v2.14.0+0/pandoc.v2.14.0.x86_64-w64-mingw32.tar.gz"
